package.json
pnpm-lock.yaml
src/service.ts
test/service.spec.ts

It turns out that app names which end with " Helper" cause crashes on MacOS. `electron-builder` has worked around this by stripping " Helper" for the executable name only (CFBundleExecutable). I wouldn't have noticed had my Electron app not been named "DJ Helper".  Just replicating the `electron-builder` behaviour here.

add fix for mac execName " Helper" issue

---

README.md

Add information about sandbox, asar issues and recommendations for environment variables to README

Documentation: Add information regarding sandboxing, asar issues, improved code examples

---

package.json
src/index.ts
src/types.ts

Improve TypeScript documentation for the `electron` object assigned to `browser`.

(docs): add docs to the typescript API

---

README.md
eslint.config.js
example-cjs/wdio.conf.ts
example/tsconfig.json
example/wdio.conf.ts
src/esm/constants.ts
src/launcher.ts
src/utils.ts
test/launcher.spec.ts

I would find the DX much better if the service could figure out the location of the Electron build based on some assumptions we can make given their setup. This patch allows users not to have to set the `appBinaryPath` if they use Electron Builder or Electron Forge as build tool. The change is backwards compatible and only kicks in if the property isn't already set.
Furthermore the launcher has tried to detect the Electron version by looking at the `electron` dependency. However our example has used `electron-nightly` so I enhanced that mechanism to also check for the version of that dependency.

(feat): detect app binary path for electron builder and forge

---

example/multiremote/api.spec.ts
example/package.json
example/wdio.conf.ts
example/wdio.multiremote.conf.ts
package.json
src/constants.ts
src/launcher.ts
src/service.ts
test/launcher.spec.ts

This patch will allow to run Electron tests in combination with another browser instance to test e.g. chat applications.

(feat): support multiremote

---

src/commands/execute.ts
src/constants.ts
test/commands/execute.spec.ts

Refactor to mitigate confusion around logging of `execute` calls, e.g. in #337

fix: move execute error into callback

---

src/constants.ts
src/service.ts
src/types.ts
test/commands/execute.spec.ts
test/main.spec.ts
test/service.spec.ts
vitest.config.ts

* Improving unit coverage mostly related to `execute`
* Excluding all CJS files and the ESM `index.ts` from coverage
* Some cleanup

test: units cleanup and coverage improvements

---

src/mock.ts

Using indirect `eval` to increase security as per [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#direct_and_indirect_eval).

fix: use indirect eval

---

docs/electron-apis/mocking-apis.md
example-cjs/e2e/api.spec.ts
example-cjs/pnpm-lock.yaml
example-electron-builder/pnpm-lock.yaml
example/e2e/api.spec.ts
example/pnpm-lock.yaml
pnpm-lock.yaml
src/types.ts

Adding mock object properties (E2Es, docs, updating types).  Including `calls`, `lastCall`, `results`, `invocationCallOrder`.  Not including [`instances`](https://vitest.dev/api/mock.html#mock-instances) as our mocks are instantiated solely via `createMock`, without using `new`.

(feat): add mock object properties

---

.github/workflows/release.yml
docs/development.md

- Release when we publish `latest`
- Pre-release when we publish `next` (or not `latest`)
- Document the release process
﻿
- I didn't quote the workflow inputs so we can still add `--dry-run`.

ci: Add pre-release to release workflow

---

test/launcher.spec.ts

Whilst the version units mock out the electron release json response, the launcher units do not - this could be the reason behind #339.  Regardless, mocking this speeds up the units so is worthwhile.

(test): speed up `onPrepare` units by mocking electron release response

---

@types/vitest/index.d.ts
docs/electron-apis/mocking-apis.md
example-cjs/e2e/api.spec.ts
example/e2e/api.spec.ts
src/commands/isMockFunction.ts
src/mock.ts
src/service.ts
src/types.ts
test/commands/isMockFunction.spec.ts

Completing the `vitest`-like mocking API.  This will be released as 6.4.0
EDIT: Fixed "Cannot find package 'async_hooks' imported from ... `p-limit`" error, it required removing and amending vitest imports

(feat): isMockFunction command

---

.github/workflows/release.yml
docs/development.md

* Add a checkbox to dry-run
* Provide a way to increment the pre-release version (e.g.: `-next.0` => `.next-1`)
* Prevent us from using the invalid release with a pre-release version
* Attempt to improve the docs

ci: Increment the pre-release version

---

.github/workflows/release.yml

This closes issue #474.﻿
The `--dry-run` flag was not added when the `dryRun` input was set.
This PR sets the `DRY_RUN_ARG` environment variable and uses it for the pre-release and release steps.
My apologies @goosewobbler. :facepalm:

ci: Use --dry-run

---

README.md
docs/common-issues.md
docs/configuration/chromedriver-configuration.md
docs/configuration/service-configuration.md
docs/electron-apis/accessing-apis.md
src/index.ts
src/preload.ts
src/types.ts
test/preload.spec.ts

Removing the guards from the preload as one is causing issues with Vite-based projects for negligible gain -- the other is redundant.

(fix): remove preload guards

---

package.json
pnpm-lock.yaml

Moves `@electron/packager` from devDependencies to dependencies so it is (recursively) installed by `npm ci`.
Otherwise this import throws a runtime error:
https://github.com/webdriverio-community/wdio-electron-service/blob/f6a5d6b0fec78b43300036faffa016b67494347d/src/application.ts#L9

fix: move @electron/packager to dependencies

---

packages/@wdio-electron_types/package.json
packages/@wdio-electron_utils/package.json
packages/wdio-electron-service/package.json
pnpm-lock.yaml
release-it.json

Rather than packing the packages separately and using the hooks (which breaks when used with `--dry-run`), we can use `release-it-pnpm`.

chore: use release-it-pnpm

---

fixtures/electron-in-dependencies/package.json
fixtures/electron-in-dev-dependencies/package.json
fixtures/old-electron/package.json
packages/wdio-electron-service/src/launcher.ts
packages/wdio-electron-service/test/launcher.spec.ts

fix: detect old electron versions and throw error

---

package.json
packages/@wdio_electron-types/README.md
packages/@wdio_electron-types/package.json
packages/@wdio_electron-utils/README.md
packages/@wdio_electron-utils/package.json
packages/wdio-electron-service/package.json
scripts/release.ts
turbo.json

Working around the `release-it` issue described in #746.  Also ensuring the released packages have README and LICENSE

fix(ci): pack after bump

---

docs/common-issues-debugging.md
packages/wdio-electron-service/main/package.json
packages/wdio-electron-service/package.json
packages/wdio-electron-service/preload/package.json

* Adding a fallback for resolvers which do not support subpath exports: https://github.com/andrewbranch/example-subpath-exports-ts-compat/tree/main/examples/node_modules/package-json-redirects
* Updating docs to expand on possible solutions to the preload not found error

fix: add entry points for N10

---

packages/@wdio_electron-types/package.json
packages/@wdio_electron-utils/package.json

The lack of a license breaks license checkers

fix: add missing license and homepage metadata

---

apps/builder-cjs/package.json
apps/builder-esm/package.json
apps/forge-cjs/package.json
apps/forge-esm/package.json
apps/no-binary-cjs/package.json
apps/no-binary-esm/package.json
e2e/package.json
package.json
packages/@wdio_electron-types/package.json
packages/@wdio_electron-utils/package.json
packages/wdio-electron-service/package.json
pnpm-lock.yaml

It seems the WDIO update from 9.0.9 / 9.0.8 => 9.1.3 breaks the E2Es, so for this patch release we're just updating the other deps.

chore: update deps

---

packages/@wdio_electron-utils/src/index.ts

`electron-builder` JSON config parsing is failing in ESM projects.

fix: JSON5 exports parse under the default key in ESM

---

packages/@wdio_electron-utils/package.json
packages/wdio-electron-service/src/cjs/session.ts

This is update for following TODO.
Updated package.json in "@wdio/electron-utils/log" to fix this TODO.
> [TODO: Fix CJS import of `log` from '@wdio/electron-utils/log'](https://github.com/mato533/wdio-electron-service/blob/bfb4b97dbf8f823b1cbb6ba9f86cfdf276285688/packages/wdio-electron-service/src/cjs/session.ts#L2)
In my understand, when `CommonJS` is set `module` at `tsconfig.json`, then `moduleResolution` will be set `node10` (same as `node`) as a default.([docs](https://www.typescriptlang.org/tsconfig/#moduleResolution))
Then `exports` field of package.json(imported module side) will be ignored. (`exports` field is added [Node v12.7.0](https://nodejs.org/en/blog/release/v12.7.0).)
So this PR adds a `typesVersions` field and tells typescript to the appropriate types file.

fix: fix CJS import of `log` at session.ts

---

README.md
docs/configuration/service-configuration.md

Hi, thank you for your work! 
With this PR I would like to add information about `appBinaryPath` for MacOS. 
I was trying to run webdriverio for my electron application on MacOS without luck, but then I suddenly realised (while digging into the source code of wdio-electron-service) that I had configured `appBinaryPath` incorrectly. It wasn't clear to me that I had to set the path this way, so I'm suggesting this information so that it might save someone a few hours/days in the future.

docs: add information about appBinaryPath for MacOS

---

e2e/test/dom.spec.ts
packages/@wdio_electron-types/src/index.ts

Update type definitions of `$$` and `$` to align
`webdriverio`.
Closes: #899

fix: update type definition of the `$$` and `$`

---

.github/workflows/ci.yml
.github/workflows/release.yml

PR includes changes which support to release multiple versions.
- CI execution at push for branches of the maintenance version
- Support for releases using branches other than main

ci: add support to release multiple versions

---

apps/builder-cjs/src/index.html
apps/builder-cjs/src/main.ts
apps/builder-cjs/src/preload.ts
apps/builder-esm/src/index.html
apps/builder-esm/src/main.ts
apps/builder-esm/src/preload.cts
apps/forge-cjs/src/index.html
apps/forge-cjs/src/main.ts
apps/forge-cjs/src/preload.ts
apps/forge-esm/src/index.html
apps/forge-esm/src/main.ts
apps/forge-esm/src/preload.cts
apps/no-binary-cjs/src/index.html
apps/no-binary-cjs/src/main.ts
apps/no-binary-cjs/src/preload.ts
apps/no-binary-esm/src/index.html
apps/no-binary-esm/src/main.ts
apps/no-binary-esm/src/preload.cts
e2e/test/api.spec.ts
packages/wdio-electron-service/src/mock.ts
packages/wdio-electron-service/src/service.ts
packages/wdio-electron-service/test/service.spec.ts

Update the `mock.update` method to parse the object provided as a parameter into a serializable object when calling the mocked method.
In addition, we fixed the condition where mock.update is executed only when the `execute` command is executed, and changed it to target all commands(*) where the electron method may be called.
*) for now, i exclude the command `deleteSession`
Closes #895

fix: add processing to parse into serializable objects when sync mock object

---

docs/common-issues-debugging.md

docs: add linux issue

---

.github/dependabot.yml
.github/workflows/release.yml
docs/development.md

This PR include following changes.
-  the dependabot configuration for maintenance version (currently v7)
-  the document about task list when major version is updated

chore: add the dependabot configuration for maintenance version

---

packages/@wdio_electron-utils/src/log.ts

I want to change the hierarchy of objects in the debug log that can be analyzed using [‘DEBUG_DEPTH’](https://github.com/debug-js/debug?tab=readme-ov-file#environment-variables).
For this purpose, if the last element of the argument passed to debug is of type Object, we want to change it so that it is output with [the appropriate formatting](https://github.com/debug-js/debug?tab=readme-ov-file#formatters).
Run with `DEBUG_DEPTH` set in the environment variable.
```bash
pnpm exec cross-env DEBUG_DEPTH=3 pnpm run exec:main
```
The third level also outputs values (the output is not like Array, Object, etc...).
```bash
wdio-electron-service [ 'setting capability' ] +1s
wdio-electron-service {
wdio-electron-service   browserName: 'chrome',
wdio-electron-service   'wdio:electronServiceOptions': …
```

feat: support object inspection at debug log

---

scripts/publish.ts

We need to be able to publish `@wdio/electron-bundler`:
https://github.com/webdriverio-community/wdio-electron-service/actions/runs/13275522535/job/37064292050#step:10:54

chore: add  `--access=public` to publish

---

package.json
packages/wdio-electron-service/package.json
pnpm-lock.yaml

Adding the lifecycle scripts back one by one to `pnpm.onlyBuiltDependencies`.
The scripts we could be running are "electron", "esbuild", "edgedriver", "geckodriver"
Looks like we only depend on the "electron" script, we can keep the others disabled

chore: update pnpm

---

package.json

Remove the field of `version` from root `package.json` which is not maintained.

chore: remove version from root package.json

---

packages/@wdio_electron-bundler/src/plugins.ts
packages/@wdio_electron-bundler/src/utils.ts
packages/@wdio_electron-bundler/test/plugins.spec.ts
packages/@wdio_electron-bundler/test/utils.spec.ts
packages/@wdio_electron-utils/rollup.config.ts

Fix CJS issue for logger.
The `@wdio/logger` is not support the CJS.
So this PR is add the plugin to replace to import instead of require.

chore: update rollup.config.js to fix CJS issue for logger

---

.github/workflows/pre-release.yml
.github/workflows/release.yml

Updating the release and pre-release tag handling for NPM so that the following logic applies:
- Release main: npm tag is `latest`
- Pre-release main: npm tag is `next`
- Release non-main: npm tag is `lts`
- Pre-release non-main: npm tag is `lts-next`
This enables us to have separate tags for the LTS / maintenance releases.  We are assuming that releases and pre-releases will only ever happen from either `main` or the preconfigured LTS / maintenance branch (currently v7).

ci: use `lts` and `lts-next` tags for NPM when releasing from a non-main branch

---

e2e/test/dom.spec.ts
e2e/test/interaction.spec.ts
packages/@wdio_electron-types/src/index.ts
pnpm-lock.yaml

This PR changed the return type of `$` and `$$` using the type exported by the `webdriverIo`.
This change will happen the type mismatch for `Browser` type between the expected one by the method `setupBrowser` of `@testing-library/webdriverio` and one of this service provides.
This issue is suspected that it is caused by type definition of testing liblary side.
So, We will ignore the type error of this method. We would like your expert FBs on the validity of this direction.
https://github.com/testing-library/webdriverio-testing-library/issues/51
close #957

fix: broken $ and $$ types

---

packages/@wdio_electron-bundler/test/index.spec.ts
packages/@wdio_electron-bundler/test/plugins.spec.ts
packages/@wdio_electron-bundler/test/utils.spec.ts
packages/@wdio_electron-utils/test/index.spec.ts
packages/wdio-electron-service/test/capabilities.spec.ts
packages/wdio-electron-service/test/commands/clearAllMocks.spec.ts
packages/wdio-electron-service/test/commands/execute.spec.ts
packages/wdio-electron-service/test/commands/isMockFunction.spec.ts
packages/wdio-electron-service/test/commands/mock.spec.ts
packages/wdio-electron-service/test/commands/mockAll.spec.ts
packages/wdio-electron-service/test/commands/resetAllMocks.spec.ts
packages/wdio-electron-service/test/commands/restoreAllMocks.spec.ts
packages/wdio-electron-service/test/launcher.spec.ts
packages/wdio-electron-service/test/main.spec.ts
packages/wdio-electron-service/test/mock.spec.ts
packages/wdio-electron-service/test/mockStore.spec.ts
packages/wdio-electron-service/test/preload.spec.ts
packages/wdio-electron-service/test/service.spec.ts
packages/wdio-electron-service/test/session.spec.ts
packages/wdio-electron-service/test/versions.spec.ts
packages/wdio-electron-service/test/window.spec.ts

Add or change following unit test cases.
- `packages/wdio-electron-service/test/launcher.spec.ts`
eliminate duplication of test code using each
- `packages/wdio-electron-service/test/mock.spec.ts`
add test for `mock.update` and improve the coverage
-  `packages/wdio-electron-service/test/service.spec.ts`
Change to appropriate test content of multi remote browser and improve the coverage

test: add missing unit test

---

.github/dependabot.yml

Following changes is included
- `puppeteer-core` should be match peer dependencies of `webdriverio`
- grouping `wdio` because when it had some issues, we want ignore all related packages.
- add config for GitHub Actions
closes #1000

chore: update configuration for dependabot

---

scripts/backport.ts

Fix following issues.
- wrong calculate the version logic.
In maintenance branch, the version of package.json is maintenance version(it is no need to `- 1`)
- revised number of PRs to be retrieved to the latest 100
Due to performance, Limit the number of cases to be acquired.

chore: fix backport script

---

e2e/test/interaction.spec.ts

Remove unnecessary await (related to changes of #967) at E2E test suites.

test: remove unnecessary await

---

.github/workflows/_release-calculate.reusable.yml

Looking to release `7.3.2` and CI is checking for a `v7` branch when we changed it to `v7.x`

ci: standardise branch names around `v{MAJOR_VERSION}.x`

---

packages/@wdio_electron-utils/package.json
pnpm-lock.yaml

`rollup-plugin-node-externals` is used by the bundler but not by utils

chore: remove unnecessary dep

---

.github/dependabot.yml

If we want to group a particular package, we may need to exclude that package from the group created by `dependency-type` with `exclude-patterns`.

chore: fix to invalid group configuration for the dependabot

---

e2e/test/interaction.spec.ts

To fix the flaky test, This PR proposed the changes to add a wait step before asserting the DOM text.

test: add wait step to the interaction e2e test

---

.github/workflows/README.md
.github/workflows/_ci-build.reusable.yml
.github/workflows/_ci-e2e.reusable.yml
.github/workflows/_ci-lint.reusable.yml
.github/workflows/_ci-unit.reusable.yml
.github/workflows/actions/download-archive/action.yml
.github/workflows/actions/upload-archive/action.yml
.github/workflows/ci.yml

Improving the approach in #978 using Github Actions Cache and Github Artifacts as a fallback.  Also implementing code review changes here.
TODO:

ci: further improvements 

---

packages/wdio-electron-service/package.json
packages/wdio-electron-service/src/capabilities.ts
packages/wdio-electron-service/src/launcher.ts
packages/wdio-electron-service/test/capabilities.spec.ts
packages/wdio-electron-service/test/launcher.spec.ts
pnpm-lock.yaml

To assign the debugger port, we should (re-)implement the onWorkerStart hook at launcher.ts and related modules.
(Recreate: #954)

feat(cdp): add ability to assign the debugger port worker by worker 

---

.npmrc

The root `.npmrc` is only used to apply a workaround for an old electron-builder [issue](https://github.com/electron-userland/electron-builder/issues/8175).  PNPM fixed this a while ago so we can remove it

chore: remove root `.npmrc`
