webdriverio-community/wdio-electron-service

src/service.ts

Sync output with electron builder

---

README.md
package.json
pnpm-lock.yaml
src/cjs/pnpm-lock.yaml
src/service.ts
test/service.spec.ts

Removing the default chromeArgs so that the user can specify whatever flags they desire in appArgs.

Enable full customisation of chromeArgs

---

README.md

The current configuration example assumes that the developer uses [`electron-builder`](https://www.electron.build/) which might not be the case.
This patch restructures the `README.md` to show a very simplistic version of a necessary configuration first and then a more sophisticated version with [`electron-builder`](https://www.electron.build/).

Simplify config example

---

.github/workflows/release.yml

fixes #324.  Needs some manual testing.

(ci): hook up distTag to release-it

---

.github/workflows/release.yml

ci: Move "--" to fix the --npm.tag

---

.github/workflows/release.yml

Reverts webdriverio-community/wdio-electron-service#428

Revert "ci: Move "--" to fix the --npm.tag"

---

example-cjs/package.json
example-cjs/pnpm-lock.yaml
example-electron-builder/package.json
example-electron-builder/pnpm-lock.yaml
example/package.json
example/pnpm-lock.yaml
package.json
pnpm-lock.yaml

(chore): update electron

---

.github/workflows/expense.yml/expense.yml

- Add workflow from [webdriverio/expense-action](https://github.com/webdriverio/expense-action)

ci: Add Expense Contribution workflow

---

src/service.ts

Make before() hook compatible with apps which did not import main/preload scripts

---

README.md
docs/common-issues-debugging.md

docs: add debugging

---

.github/workflows/ci.yml
README.md
docs/common-issues-debugging.md
docs/configuration/chromedriver-configuration.md
docs/development.md
packages/wdio-electron-service/package.json

Final updates for the WDIO v9 release

v9 release updates

---

packages/wdio-electron-service/src/launcher.ts
packages/wdio-electron-service/test/launcher.spec.ts

feat: apply `--no-sandbox` when appArgs are not specified

---

packages/wdio-electron-service/test/session.spec.ts

add some test.
@goosewobbler 
I dont have write access to this repo. so, i have created this PR.

test: add test for parameter of the init function

---

.github/workflows/pre-release.yml
.github/workflows/release.yml
docs/development.md
package.json
packages/@wdio_electron-types/package.json
packages/@wdio_electron-utils/package.json
packages/wdio-electron-service/package.json
pnpm-lock.yaml
scripts/publish.ts
scripts/release.ts
version.config.json

ci: replace release-it

---

apps/builder-cjs/package.json
apps/builder-esm/package.json
apps/forge-cjs/package.json
apps/forge-esm/package.json
apps/no-binary-cjs/package.json
apps/no-binary-esm/package.json
e2e/package.json
e2e/test/api.spec.ts
package.json
packages/@wdio_electron-types/package.json
packages/@wdio_electron-utils/package.json
packages/wdio-electron-service/package.json
pnpm-lock.yaml

Updating major versions of some deps

chore: update deps

---

docs/development.md
package.json
pnpm-lock.yaml
scripts/backport.ts

Add the docs for maintenance policy and the script for backport operation and documentation about it.
closes: #910 #911 #922

chore: docs for Maintenance policy and automate backport operation

---

apps/builder-cjs/package.json
apps/builder-esm/package.json
apps/forge-cjs/package.json
apps/forge-esm/package.json
apps/no-binary-cjs/package.json
apps/no-binary-esm/package.json
e2e/package.json
e2e/test/api.spec.ts
package.json
packages/@wdio_electron-types/package.json
packages/@wdio_electron-utils/package.json
packages/wdio-electron-service/package.json
pnpm-lock.yaml

Updating major versions of some deps for v7

chore: update deps(v7)

---

packages/wdio-electron-service/package.json
packages/wdio-electron-service/src/capabilities.ts
packages/wdio-electron-service/src/launcher.ts
packages/wdio-electron-service/test/capabilities.spec.ts
packages/wdio-electron-service/test/launcher.spec.ts
pnpm-lock.yaml

feat: add ability to assign the debugger port worker by worker

---

.github/workflows/release-shared.yml

Add the step of creating maintenance branch.

ci: create maintenance branch automatically

---

.github/workflows/_release-orchestration.reusable.yml
.github/workflows/_release-prepare.reusable.yml
.github/workflows/_release-publish.reusable.yml

@goosewobbler 
We have modified the workflow and confirmed that the following flow is now operational.
related to: #960

ci: update release workflow

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml

ci: add major release feature branch and fix maintenance branch name

---

e2e/package.json
e2e/rollup.config.js
e2e/test/dom.spec.ts
packages/wdio-electron-service/package.json
pnpm-lock.yaml

Removing this unmaintained library and also adding await for `$` and `$$` as they return promises.

test: remove `@testing-library/webdriverio`

---

.github/workflows/ci.yml

Add missing build test on the MacOS.

ci: add build test for MacOS

---

packages/@wdio_electron-utils/test/getBinaryPath.spec.ts

test: fix mac-universal binary path

---

.github/workflows/_ci-lint.reusable.yml
.gitignore
e2e/package.json
package.json
turbo.json

chore: enable tooling caches

---

.github/workflows/pr-title.yml

ci: add PR title check

---

README.md
docs/common-issues-debugging.md

docs: mention WDIO version requirement for `autoXvfb`
